[package]
name = "aggregator-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
sp1-zkvm = { version = "=6.1.0", features = ["verify"] }
sp1-lib = { version = "=6.1.0", features = ["verify"] }
sp1-primitives = "=6.4.0"
wash-predicate = { path = "../../predicate" }
sha2 = { version = "0.10", default-features = false }

[patch.crates-io]
k256 = { git = "https://github.com/sp1-patches/elliptic-curves", tag = "patch-k256-13.4-sp1-6.0.0" }
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", tag = "patch-2.0.2-sp1-6.0.0" }

[profile.release]
lto = "thin"
opt-level = 3
