[workspace]
resolver = "2"
members = ["core", "history-core", "history-methods", "host", "methods"]

[workspace.dependencies]
checkpoint-core = { path = "core" }
checkpoint-methods = { path = "methods" }
history-core = { path = "history-core" }
history-methods = { path = "history-methods" }

alloy = { version = "=2.0.0", default-features = false }
alloy-consensus = { version = "=2.0.0", default-features = false, features = ["serde"] }
alloy-primitives = { version = "=1.5.3", default-features = false, features = ["rlp", "serde", "tiny-keccak"] }
alloy-rlp = { version = "0.3.8", default-features = false }
alloy-sol-types = { version = "=1.5.3", default-features = false }
anyhow = "1"
serde = { version = "1", features = ["derive"] }

sp1-build = "=6.1.0"
sp1-sdk = { version = "=6.1.0", default-features = false }

[profile.release]
debug = 1
lto = true

[patch.crates-io]
alloy-signer-aws = { path = "../vendor/alloy-signer-aws" }
