[workspace]
resolver = "2"
members = ["core", "host", "methods"]

[workspace.dependencies]
checkpoint-core = { path = "core" }
checkpoint-methods = { path = "methods" }

alloy = { version = "2.0", default-features = false }
alloy-consensus = { version = "2.0", default-features = false, features = ["serde"] }
alloy-primitives = { version = "1.5.3", default-features = false, features = ["rlp", "serde", "tiny-keccak"] }
alloy-rlp = { version = "0.3.8", default-features = false }
alloy-sol-types = { version = "1.5.3", default-features = false }
anyhow = "1"
serde = { version = "1", features = ["derive"] }

risc0-build = "3.0"
risc0-op-steel = { git = "https://github.com/boundless-xyz/steel", rev = "f6fc6297c938d7acc0563337da136d034c3cb67b", default-features = false }
risc0-steel = { git = "https://github.com/boundless-xyz/steel", rev = "f6fc6297c938d7acc0563337da136d034c3cb67b", default-features = false }
risc0-zkvm = { version = "3.0", default-features = false }

[profile.release]
debug = 1
lto = true
